# Generated by Django 2.2.1 on 2019-06-07 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('modified_date', models.DateTimeField()),
                ('localization', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.IntegerField()),
                ('modified_date', models.DateTimeField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('card_namber', models.CharField(max_length=25)),
                ('transaction_time', models.DateTimeField()),
                ('value', models.FloatField()),
                ('method', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Terminal')),
            ],
        ),
    ]
