# Generated by Django 2.2.1 on 2019-06-08 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=255)),
                ('branch_of_business', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='Raport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers', models.BigIntegerField()),
                ('new_customers', models.IntegerField()),
                ('regular_customers', models.IntegerField()),
                ('new_regular_customers', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('transaction_counts', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_namber', models.CharField(max_length=25)),
                ('value', models.FloatField()),
                ('method', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('coordinates', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Terminal')),
            ],
        ),
    ]
