# Generated by Django 2.0.7 on 2019-06-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20190608_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.AddField(
            model_name='employer',
            name='eid',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terminal',
            name='eid',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employer',
            name='modified_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='modified_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='modified_at',
            field=models.DateTimeField(),
        ),
    ]
