# Generated by Django 2.0.7 on 2019-06-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_employee_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='card_namber',
            new_name='card_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='payment',
            name='lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='lon',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
