# Generated by Django 2.0.7 on 2019-06-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20190608_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='employer',
            name='lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='lon',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
