# Generated by Django 2.0.7 on 2019-06-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20190608_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Payment')),
            ],
        ),
    ]
